apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka-strimzi-cluster.fullname" . }}
  labels:
    {{- include "kafka-strimzi-cluster.labels" . | nindent 4 }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: "enabled"
spec:
  cruiseControl:
    {{- with .Values.cruiseControl.brokerCapacity }}
    brokerCapacity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.cruiseControl.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    template:
      pod:
        {{- with .Values.cruiseControl.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.cruiseControl.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.cruiseControl.topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    resources:
      {{- toYaml .Values.cruiseControl.resources | nindent 6 }}
  entityOperator:
    topicOperator:
      {{- with .Values.topicOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.topicOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.topicOperator.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      resources:
        {{- toYaml .Values.topicOperator.resources | nindent 8 }}
    userOperator:
      {{- with .Values.userOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.userOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.userOperator.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      resources:
        {{- toYaml .Values.userOperator.resources | nindent 8 }}
  kafka:
    {{ with .Values.kafka.jmxOptions }}
    jmxOptions: 
    {{- toYaml . | nindent 6 }}
    {{- end }}          
    config:      
      auto.create.topics.enable: {{ .Values.kafka.allowAutoCreate | default false }}
      {{- with .Values.kafka.config }}
      {{- toYaml . | nindent 6 }}
      {{- end }}      
    {{- if .Values.kafka.rack.enabled }}
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
    rack:
      topologyKey: {{ .Values.kafka.rack.topologyKey }}
    {{- end }}
    {{- if .Values.kafka.metricsConfig.enabled }}
    metricsConfig:
      type: {{ .Values.kafka.metricsConfig.type | default "jmxPrometheusExporter" }}
      valueFrom:
        configMapKeyRef:
          name: {{ include "kafka-strimzi-cluster.fullname" . }}-metrics-config
          key: metrics.yaml
    {{- end }}
    listeners:
      {{- if .Values.kafka.listeners.internal.plain.enabled }}
      - name: plain
        port: 9092
        tls: false
        type: internal
      {{- end }}
      {{- if .Values.kafka.listeners.internal.tls.enabled }}
      - name: tls
        port: 9093
        tls: true
        type: internal
        {{- if .Values.kafka.listeners.internal.tls.secretName }}
        configuration:
          brokerCertChainAndKey:
            secretName: {{ .Values.kafka.listeners.internal.tls.secretName }}
            certificate: tls.crt
            key: tls.key
        {{- end }}
        {{- if .Values.kafka.listeners.internal.tls.certManager.enabled }}
        configuration:
          brokerCertChainAndKey:
            secretName: {{ include "kafka-strimzi-cluster.fullname" . }}-listener-internal-tls
            certificate: tls.crt
            key: tls.key
        {{- end }}
        {{- if .Values.kafka.listeners.internal.tls.authentication.enabled }}
        authentication:
        {{- range $key, $value := .Values.kafka.listeners.internal.tls.authentication }}
          {{- if ne $key "enabled" }}
          {{ $key | nindent 10 }}: {{ $value }}
          {{- end }}
        {{- end }}
        {{- end }}        
      {{- end }}
    {{- if .Values.kafka.authorization.enabled }}
    authorization:
      type: simple
      superUsers:
        - {{ include "kafka-strimzi-cluster.fullname" . }}-kadmin
    {{- end }}
    {{ with .Values.kafka.template }}
    template:
    {{- toYaml . | nindent 6 }}
    {{- end }}