kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kafka-strimzi-cluster.fullname" . }}-metrics-config
data:
{{- if .Values.kafka.metricsConfig.config }}
  metrics-config: |-
{{ toYaml .Values.kafka.metricsConfig.config | indent 4 }}
{{- else }}
  metrics-config: ""
{{- end }}