kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kafka-strimzi-cluster.fullname" . }}-metrics-config
spec:
  data:
    metrics.yaml: {{ toYaml .Values.kafka.metricsConfig.config | indent 4 }}