{{- if .Values.nodePools.controller.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ include "kafka-strimzi-cluster.fullname" . }}
spec:
  replicas: 3
  roles:
    - controller
  storage:
    {{- toYaml .Values.nodePools.controller.storage | nindent 4 }}
  resources:
    {{- toYaml .Values.nodePools.controller.resources | nindent 4 }}
{{- end }}
