kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kafka-strimzi-cluster.fullname" . }}-metrics-config
spec:
  data:
    metrics-config: |-
      #Metrics Config may be empty if so defaults are used
{{ .Values.kafka.metricsConfig.config | indent 6 }}