{{- if .Values.nodePools.controller.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: {{ include "kafka-strimzi-cluster.fullname" . }}
    {{- include "kafka-strimzi-cluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nodePools.controller.replicas | default 3 }}
  roles:
    - controller
  storage:
    {{- toYaml .Values.nodePools.controller.storage | nindent 4 }}
  resources:
    {{- toYaml .Values.nodePools.controller.resources | nindent 4 }}
  template:
    pod:
        {{- with .Values.nodePools.controller.template.pod.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.nodePools.controller.template.pod.priorityClassName }}
        priorityClassName: {{ .Values.nodePools.controller.template.pod.priorityClassName }}
        {{- end }}
        {{- with .Values.nodePools.controller.template.pod.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nodePools.controller.template.pod.topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.nodePools.controller.template.pod.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
