apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: {{ include "kafka-strimzi-cluster.fullname" . }}
  labels:
    strimzi.io/cluster: {{ include "kafka-strimzi-cluster.fullname" . }}
    {{- include "kafka-strimzi-cluster.labels" . | nindent 4 }}
spec:
  skipHardGoalCheck: {{ .Values.cruiseControl.skipHardGoalCheck }}
  {{- with .Values.cruiseControl.goals }}
  goals:
    {{- toYaml . | nindent 4 }}
  {{- end }}
