apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka-cluster.fullname" . }}
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  cruiseControl:
    template:
      pod:
        {{- with .Values.cruiseControl.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.cruiseControl.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.cruiseControl.topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    resources:
      {{- toYaml .Values.cruiseControl.resources | nindent 6 }}
  entityOperator:
    topicOperator:
      {{- with .Values.topicOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.topicOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.topicOperator.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      resources:
        {{- toYaml .Values.topicOperator.resources | nindent 8 }}
    userOperator:
      {{- with .Values.userOperator.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.userOperator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.userOperator.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      resources:
        {{- toYaml .Values.kafka.resources | nindent 8 }}
  kafka:
    template:
      pod:
        {{- with .Values.kafka.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.kafka.priorityClassName }}
        priorityClassName: {{ .Values.kafka.priorityClassName }}
        {{- end }}
        {{- with .Values.kafka.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.kafka.topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    resources:
      {{- toYaml .Values.kafka.resources | nindent 6 }}
    # authorization:
    #   type: simple
    #   superUsers:
    #     - lsadmin
    config:
      min.insync.replicas: 2
      auto.create.topics.enable: {{ .Values.kafka.allowAutoCreate | default false }}
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
    rack:
      topologyKey: topology.kubernetes.io/zone
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
        authentication:
          type: tls
      # - name: external
      #   port: 9094
      #   tls: false
      #   type: cluster-ip
      #   authentication:
      #     type: scram-sha-512


    replicas: {{ .Values.kafka.replicas }}
    storage:
      {{- toYaml .Values.kafka.storage | nindent 6 }}

  zookeeper:
    template:
      pod:
        {{- with .Values.zookeeper.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.zookeeper.priorityClassName }}
        priorityClassName: {{ .Values.zookeeper.priorityClassName }}
        {{- end }}
        {{- with .Values.zookeeper.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.zookeeper.topologySpreadConstraints }}
        topologySpreadConstraints:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    resources:
      {{- toYaml .Values.zookeeper.resources | nindent 6 }}
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      {{- toYaml .Values.zookeeper.storage | nindent 6 }}
